### ISSUE TITLE
Major compile errors 

### ISSUE THREAD

**Issue by Napk1ns** [FakeNewsGroup2/FakeNews#3]
Main.cpp no longer compiles due to lack of curl hooks.
Total of 10 problematic lines in main currently.

net.cpp no longer compiles due to lack of curl hooks.
17 problematic lines.
fs.cpp - Many #include based fatal errors
4 problematic lines.

Neuralnet.cpp - many definition errors, possibly due to change in context
Neuralnet.h - ambiguous definition errors, probably context based.

ExampleEstimator.h - &string undefined 

Article.h - Overloaded function definition not found

I think most of these are libcurl based, besides the neuralnetwork implimentation

**Comment by zemja** [comment]
I'll fix it, I think it's because I removed curl from the repository, since it's an external library. There are two solutions: a) you get curl and put it somewhere the compiler can find it. b) I just add it back to the repo. The first is better, but I'll do the second because it's easier for everybody.

**Comment by zemja** [comment]
Thanks to c9efed2 and 41b0b13, now builds and works for me.
